export { default as CloseButton } from './close-button.svg'
export { default as Facebook } from './facebook.svg'
export { default as Instagram } from './instagram.svg'
export { default as Twitter } from './twitter.svg'
export { default as YouTube } from './youtube.svg'
